### ISSUE TITLE
fix encoding for Chinese chars

### ISSUE THREAD

**Issue by berleant** [feross/stream-with-known-length-to-buffer#1]
Hey,

I found this problem when trying to render a file with Chinese characters (see screenshot)
https://github.com/karissa/dat-explorer/issues/2

Does buffer have a 'utf-8' encoding option? Would that fix it?

![screenshot](https://cloud.githubusercontent.com/assets/1402948/12340650/0045a97a-bad1-11e5-9b7b-51a63a80eebb.png)

**Comment by feross** [comment]
Maybe `dat-explorer` needs to set the encoding of the webpage to utf-8? cc @karissa This issue doesn't exist on https://instant.io for me. See:

<img width="1094" alt="screen shot 2016-02-07 at 4 39 27 pm" src="https://cloud.githubusercontent.com/assets/121766/12876649/6048aad4-cdb9-11e5-93d9-77ee4448c8b6.png">

The Chinese characters show up just fine.
